version: '3.8'

x-healthcheck: 
  &healthcheck
  test: curl -f http://localhost/
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 10s

services:
  db:
    image: postgres:14.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_USER:-qweasdzxc1}
    restart: always
    healthcheck:
      << : *healthcheck
      test: pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}

  web:
    image: ${IMAGE:-ghcr.io/n57uctf/anime_boys:main}
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "1111:15400"
